export const challengeQueries = [
  "is als hereditary",
  "targets for ALS",
  "what is the best target for copd",
  "what are the treatments for lupus",
  "what is the connection between copd and lupus",
  "explain paracetamol sideeffects",
  "mechanism of action of paracetamol in fever",
  "which pathways connect il6 to rheumatoid arthritis",
  "does tnf inhibition help ulcerative colitis",
  "compare targets in crohn disease vs ulcerative colitis",
  "alopecia targets that are druggable and do not affect the blood brain barrier",
  "find druggable targets for systemic sclerosis that avoid cardiac toxicity signals",
  "link psoriasis cytokine targets to depression-related pathways",
  "what target-drug paths connect asthma and eosinophilic inflammation",
  "for sle and nephritis, map shared targets and approved modulators",
  "which compounds modulate nlrp3 in gout without strong hepatotoxicity flags",
  "connect apoe, microglia pathways, and alzheimer therapeutic compounds",
  "show mechanism links between ibd and colorectal cancer targets",
  "map druggable nodes between endometriosis and chronic pain signaling",
  "find targets in idiopathic pulmonary fibrosis connected to emt pathways",
  "show target-pathway-drug links for als focusing on neuroinflammation",
  "which targets for atopic dermatitis intersect asthma genetics",
  "connect lupus treatments to interferon pathway nodes and safety caveats",
  "find compounds for sod1-related als and assess bbb relevance",
  "explore latent connections between copd oxidative stress targets and parkinson pathways",
] as const;
